runtime: python39

entrypoint: gunicorn -b :$PORT main:app

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 3

env_variables:
  FLASK_ENV: production
  SECRET_KEY: "your-secret-key"

handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto
